config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions"}
  

  root 'blogs#index'
  get 'blogs/' => 'blogs#index'
  post 'blogs/' => 'blogs#create', as: 'blog_create'
  get 'blogs/new' => 'blogs#new', as: 'blog_new'
  get 'blogs/:id' => 'blogs#show', as: 'blog'
  delete 'blogs/:id' => 'blogs#destroy'
  patch 'blogs/:id' => 'blogs#update'
  post 'blogs/:id/comments' => 'comments#create', as: 'comment_create'
  get 'blogs/:id/edit' => 'blogs#edit', as: 'blog_edit'
  get 'users/:id' => 'users#show', as: 'user'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	validates :title, presence: true, length: { in: 5..100 }
	validates :content, presence: true, length: { in: 5..500 }
	validates :display_id, presence: true, length: { in: 5..100 }

	belongs_to :user
	has_many :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :content, :user_id, :blog_id, presence: true
	
	belongs_to :user
 	belongs_to :blog
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:user_id]
  
  validates :user_id,
  	:presence => true,
  	:uniqueness => {
  		:case_sensitive => false
  	}
  validates :email,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    }
 
  attr_accessor :login
  
  has_many :blogs
  has_many :comments

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_hash).where(["user_id = :value", { :value => login.downcase }]).first
      else
        where(conditions.to_hash).first
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    #Redirect back to the page they were on prior to login
    request.referrer
  end

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_id, :email, :password, :password_confirmation, :remember_me)}
  	devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :email, :password, :remember_me) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:user_id, :email, :password, :password_confirmation, :current_password)}
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	include BlogsHelper

	before_action :all_blogs, only: [:index]
	before_action :find_blog, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	#skip_before_filter :verify_authenticity_token, :only => [:destroy]

	def new
		@blog = Blog.new
	end

	def create
		create_display_id
		@blog = Blog.new(blog_params)
		if @blog.save
			redirect_to blog_path(@blog.display_id)
		else
			render 'new'
		end
	end

	def show
		@comments = @blog.comments
		@comment = Comment.new
	end

	def edit
		
	end

	def update
		create_display_id
		if @blog.update(blog_params)
			redirect_to blog_path(@blog.display_id)
			p params
		else
			render 'edit'
		end
			
	end

	def destroy
		@blog.destroy
		redirect_to root_path
	end

	private

	# replacing the index action
	def all_blogs
		@blogs = Blog.all.order("created_at DESC")
	end

	def blog_params
		params.require(:blog).permit(:title, :content, :display_id, :user_id)
	end

	# Clean up the title for a more 
	def create_display_id
		params[:blog][:title] = params[:blog][:title].strip
		params[:blog][:content] = params[:blog][:content].strip
		@display = params[:blog][:title]
		@display = @display.to_s.gsub("'s","s").gsub("'","").gsub(/[^0-9A-Za-z]/, " ").squeeze(" ").strip.gsub(" " ,'-').downcase
		params[:blog][:display_id] = @display
		params[:blog][:user_id] = current_user.id
	end
	
	def find_blog
		@blog = Blog.find_by_display_id(params[:id])
		@user = current_user
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
		@blog = Blog.find_by_display_id(params[:id])
		@comment = @blog.comments.build(comment_params)
		@comment.blog = @blog
    	@comment.user = current_user

		respond_to do |format|
			if @comment.save
				@saved = true #storing bool for js.erb
    			format.html { redirect_to blog_path(@blog.display_id) }
				format.js { render status: :created }
			else
				@saved = false
				format.js { render status: :unprocessable_entity}
			end
		end
	end
	
	
	private
	def comment_params
		params.require(:comment).permit(:content)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    respond_to :json

    def new
        super
    end

    def create
        self.resource = warden.authenticate!(auth_options)
        sign_in(resource_name, resource)
        yield resource if block_given?
       #No longer redirecting from the controller; app.js handles this function 
       respond_with resource, location: after_sign_in_path_for(resource)
    end

    protected
    def auth_options
        { scope: resource_name, recall: "blogs#index" }
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    #Display user profile with all relevant data
    def show
        find_user
        render 'show'
    end

    def update
    end

    private
    def find_user
        @user = User.find_by_user_id(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def profile_url(user_id)
        #Populate UID into NavBar
        sprintf("/users/%s",user_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper

    def edit_blog_url(displayID)
        sprintf("/blogs/%s/edit",displayID)
    end

    def blog_url(displayID)
        sprintf("/blogs/%s",displayID)
    end

    def create_comment_url(displayID)
        sprintf("/blogs/%s/comments",displayID)
    end
    
    def user_profile_url(userID)
        sprintf("/users/%s",userID)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_blog.html.erb
<%= link_to blog.title, blog_path(blog.display_id) %><br>

app/views/blogs/_form.html.erb
<%= simple_form_for @blog do |f| %>
  <%= f.input :title %>
  <%= f.input :content, as: :text %>
  <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

</br>
<%= link_to "Cancel", root_path, class: 'btn btn-success' %>

app/views/blogs/edit.html.erb
<%= simple_form_for @blog, :url => blog_path(@blog.display_id) do |f| %>
  <%= f.input :title, readonly: true %>
  <%= f.input :content, as: :text %>
  <%= f.button :submit, 'Save', class: 'btn btn-success' %>
  <%= link_to "Delete Blog", blog_path(@blog.display_id), method: :delete, class: 'btn btn-success' %>
  <%= link_to "Cancel", blog_path, class: 'btn btn-success' %>
<% end %>

app/views/blogs/index.html.erb
 <div class="col-md-8">
<% @blogs.each do |blog| %>
	<h2> <a href= <%= blog_url(blog.display_id) %> ><%= blog.title %></a> </h2>
	<p class="lead"> by <a href= <%= user_profile_url(blog.user.user_id) %> > <%= blog.user.user_id %> </a> </p>

	<p><span class="glyphicon glyphicon-time"></span> <%= blog.created_at.strftime('%B %d, %Y %l:%M %p') %>
	</p>
	<hr>
	<img class="img-responsive" src="http://placehold.it/900x300" alt="">
	<hr>
	<p><%= blog.content %> </span></a>
	<hr>
	 <a class="btn btn-primary" href=<%= blog_url(blog.display_id) %> >Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
	<hr>
<% end %>

</div>

app/views/blogs/new.html.erb
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1> <%= @blog.title %>
	<% if user_signed_in? %>
		<% if current_user.id == @blog.user.id %>
			<a href= <%= edit_blog_url(@blog.display_id) %>><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
		<% end %>
	<% end%>
</h1>
<p>Submitted <%= time_ago_in_words(@blog.created_at) %> Ago by <a href= <%= user_profile_url(@blog.user.user_id) %>> <%= @blog.user.user_id %></a></p>

</br>
	<p><%= @blog.content %></p>
</br>

<hr>
	<div class="well">
        <h4>Leave a Comment:</h4>
			<%= render '/comments/form' %>
	</div>
<hr>

<h3 id="comments-count"><%= pluralize(@comments.count,"comment")%></h3>
<div id="comments-list">
<%= render @blog.comments %>
</div>		

app/views/comments/_comment.html.erb
<div class="media">
    <a class="pull-left" href="#">
        <img class="media-object" src="http://placehold.it/64x64" alt="">
    </a>
    <div class="media-body">
        <h4 class="media-heading"><%= comment.user.user_id %>
            <small><%= comment.created_at.strftime('%B %d, %Y %l:%M %p') %></small>
            </h4>
            <%= comment.content %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_for @comment, :url => {:controller => "comments", :action => "create"}, remote: true do |f| %>
    <div class="form-group">
        <%= f.text_area :content, :class => 'form-control', name: "comment[content]", rows: 3   %>
    </div>
        <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

 

app/views/comments/create.js.erb
<% if @saved %>
    // Check for existing alert - remove if it exists
    $('.alert').remove();

    $('#comments-list').append("<%= j render @comment %>");
    $('.form-control').val("")
    $('#comments-count').html("<%= @comment.blog.comments.count %> comments");
<% else %>
    //Check for existing alert - remove if it exists
    $('.alert').remove();

    $('<div class="alert alert-danger" role="alert">We were unable to process your request</div>').insertBefore('.well');
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href= <%= root_path %>>The Noisy Atheist</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href= <%= root_path %> >Home <span class="sr-only">(current)</span></a></li>
        <li><a href=<%= blog_new_path %>>New Blog</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        
    <li class="dropdown">
        <% if !user_signed_in? %>   
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign In</a>
            <ul class="dropdown-menu">
        		  <%= render '/sessions/new' %>
            </ul>
        <% else %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.user_id %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href= <%= profile_url(current_user.user_id) %> >Profile</a></li>
            <li><a href=<%= blog_new_path %>>Create new blog</a></li>
            <li><a href= <%= edit_user_registration_path %>>Account Settings</a></li>
            <li role="separator" class="divider"></li>
            <li><a href= <%= destroy_user_session_path %> data-method=delete>Logout</a></li>
          </ul>   
        <% end %>
    </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheNoisyAtheist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= notice %></div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert"><%= alert %></div>
<% end %> 

  <div class="container">
        <div class="row">
  
          <%= yield %>

          

        </div> <!-- end row -->
  </div> <!-- end container -->

</body>
</html>

app/views/users/show.erb
<div id="content">
<label>Name:</label><%= @user.user_id %><br>
<label>Email:</label>
    <% if user_signed_in? && current_user.user_id == @user.user_id %>
        <input type='text' value='<%= @user.email %>'>
    <% else %>
        <%= @user.email %>
    <% end %>
<br>
<label>Last sign in: </label><%= @user.current_sign_in_at.strftime('%a %m/%d/%y %l:%M%p') %><br>
</div>

<div id="user_history">
    <h2>Blog History</h2>
    <div id="blog_history">
    <%= render @user.blogs.order('created_at') %>
    </div>
    <div id="comment_history">
    <h2>Comment History</h2>
    <p>Comment count: <%= @user.comments.count %>
    </div>
</div>